services:
  postgres:
    image: postgres:16
    container_name: hris_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hris
    ports:
      - "5432:5432"
    volumes:
      - hris_pgdata:/var/lib/postgresql/data
      - ../sql:/sql

volumes:
  hris_pgdata:
